/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeleviseursRouteImport } from './routes/televiseurs'
import { Route as SecuriteRouteImport } from './routes/securite'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProjetsRouteImport } from './routes/projets'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ElectroniqueRouteImport } from './routes/electronique'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BtpRouteImport } from './routes/btp'
import { Route as BoutiqueRouteImport } from './routes/boutique'
import { Route as BatteriesRouteImport } from './routes/batteries'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ActivitesRouteImport } from './routes/activites'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProduitIdRouteImport } from './routes/produit.$id'
import { Route as CommandeIdRouteImport } from './routes/commande.$id'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminProductsRouteImport } from './routes/admin.products'

const TeleviseursRoute = TeleviseursRouteImport.update({
  id: '/televiseurs',
  path: '/televiseurs',
  getParentRoute: () => rootRouteImport,
} as any)
const SecuriteRoute = SecuriteRouteImport.update({
  id: '/securite',
  path: '/securite',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetsRoute = ProjetsRouteImport.update({
  id: '/projets',
  path: '/projets',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectroniqueRoute = ElectroniqueRouteImport.update({
  id: '/electronique',
  path: '/electronique',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BtpRoute = BtpRouteImport.update({
  id: '/btp',
  path: '/btp',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueRoute = BoutiqueRouteImport.update({
  id: '/boutique',
  path: '/boutique',
  getParentRoute: () => rootRouteImport,
} as any)
const BatteriesRoute = BatteriesRouteImport.update({
  id: '/batteries',
  path: '/batteries',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitesRoute = ActivitesRouteImport.update({
  id: '/activites',
  path: '/activites',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProduitIdRoute = ProduitIdRouteImport.update({
  id: '/produit/$id',
  path: '/produit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandeIdRoute = CommandeIdRouteImport.update({
  id: '/commande/$id',
  path: '/commande/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/activites': typeof ActivitesRoute
  '/admin': typeof AdminRouteWithChildren
  '/batteries': typeof BatteriesRoute
  '/boutique': typeof BoutiqueRoute
  '/btp': typeof BtpRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/electronique': typeof ElectroniqueRoute
  '/login': typeof LoginRoute
  '/projets': typeof ProjetsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/securite': typeof SecuriteRoute
  '/televiseurs': typeof TeleviseursRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/users': typeof AdminUsersRoute
  '/commande/$id': typeof CommandeIdRoute
  '/produit/$id': typeof ProduitIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/activites': typeof ActivitesRoute
  '/batteries': typeof BatteriesRoute
  '/boutique': typeof BoutiqueRoute
  '/btp': typeof BtpRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/electronique': typeof ElectroniqueRoute
  '/login': typeof LoginRoute
  '/projets': typeof ProjetsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/securite': typeof SecuriteRoute
  '/televiseurs': typeof TeleviseursRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/users': typeof AdminUsersRoute
  '/commande/$id': typeof CommandeIdRoute
  '/produit/$id': typeof ProduitIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/activites': typeof ActivitesRoute
  '/admin': typeof AdminRouteWithChildren
  '/batteries': typeof BatteriesRoute
  '/boutique': typeof BoutiqueRoute
  '/btp': typeof BtpRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/electronique': typeof ElectroniqueRoute
  '/login': typeof LoginRoute
  '/projets': typeof ProjetsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/securite': typeof SecuriteRoute
  '/televiseurs': typeof TeleviseursRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/users': typeof AdminUsersRoute
  '/commande/$id': typeof CommandeIdRoute
  '/produit/$id': typeof ProduitIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/activites'
    | '/admin'
    | '/batteries'
    | '/boutique'
    | '/btp'
    | '/checkout'
    | '/contact'
    | '/electronique'
    | '/login'
    | '/projets'
    | '/reset-password'
    | '/securite'
    | '/televiseurs'
    | '/admin/products'
    | '/admin/users'
    | '/commande/$id'
    | '/produit/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/activites'
    | '/batteries'
    | '/boutique'
    | '/btp'
    | '/checkout'
    | '/contact'
    | '/electronique'
    | '/login'
    | '/projets'
    | '/reset-password'
    | '/securite'
    | '/televiseurs'
    | '/admin/products'
    | '/admin/users'
    | '/commande/$id'
    | '/produit/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/activites'
    | '/admin'
    | '/batteries'
    | '/boutique'
    | '/btp'
    | '/checkout'
    | '/contact'
    | '/electronique'
    | '/login'
    | '/projets'
    | '/reset-password'
    | '/securite'
    | '/televiseurs'
    | '/admin/products'
    | '/admin/users'
    | '/commande/$id'
    | '/produit/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ActivitesRoute: typeof ActivitesRoute
  AdminRoute: typeof AdminRouteWithChildren
  BatteriesRoute: typeof BatteriesRoute
  BoutiqueRoute: typeof BoutiqueRoute
  BtpRoute: typeof BtpRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  ElectroniqueRoute: typeof ElectroniqueRoute
  LoginRoute: typeof LoginRoute
  ProjetsRoute: typeof ProjetsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SecuriteRoute: typeof SecuriteRoute
  TeleviseursRoute: typeof TeleviseursRoute
  CommandeIdRoute: typeof CommandeIdRoute
  ProduitIdRoute: typeof ProduitIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/televiseurs': {
      id: '/televiseurs'
      path: '/televiseurs'
      fullPath: '/televiseurs'
      preLoaderRoute: typeof TeleviseursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/securite': {
      id: '/securite'
      path: '/securite'
      fullPath: '/securite'
      preLoaderRoute: typeof SecuriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projets': {
      id: '/projets'
      path: '/projets'
      fullPath: '/projets'
      preLoaderRoute: typeof ProjetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/electronique': {
      id: '/electronique'
      path: '/electronique'
      fullPath: '/electronique'
      preLoaderRoute: typeof ElectroniqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/btp': {
      id: '/btp'
      path: '/btp'
      fullPath: '/btp'
      preLoaderRoute: typeof BtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique': {
      id: '/boutique'
      path: '/boutique'
      fullPath: '/boutique'
      preLoaderRoute: typeof BoutiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batteries': {
      id: '/batteries'
      path: '/batteries'
      fullPath: '/batteries'
      preLoaderRoute: typeof BatteriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activites': {
      id: '/activites'
      path: '/activites'
      fullPath: '/activites'
      preLoaderRoute: typeof ActivitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/produit/$id': {
      id: '/produit/$id'
      path: '/produit/$id'
      fullPath: '/produit/$id'
      preLoaderRoute: typeof ProduitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commande/$id': {
      id: '/commande/$id'
      path: '/commande/$id'
      fullPath: '/commande/$id'
      preLoaderRoute: typeof CommandeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminProductsRoute: typeof AdminProductsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminProductsRoute: AdminProductsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  ActivitesRoute: ActivitesRoute,
  AdminRoute: AdminRouteWithChildren,
  BatteriesRoute: BatteriesRoute,
  BoutiqueRoute: BoutiqueRoute,
  BtpRoute: BtpRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  ElectroniqueRoute: ElectroniqueRoute,
  LoginRoute: LoginRoute,
  ProjetsRoute: ProjetsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SecuriteRoute: SecuriteRoute,
  TeleviseursRoute: TeleviseursRoute,
  CommandeIdRoute: CommandeIdRoute,
  ProduitIdRoute: ProduitIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
